const type=new URLSearchParams(location.search).get('game')||'pong',stage=document.querySelector('#stage'),canvas=document.querySelector('#mini-canvas'),ctx=canvas.getContext('2d'),dom=document.querySelector('#dom-game'),overlay=document.querySelector('#mini-overlay'),scoreEl=document.querySelector('#mini-score'),bestEl=document.querySelector('#mini-best');let score=0,active=false,raf,timer,clean=()=>{};
const info={pong:['Neon Pong','Move with W/S or ↑/↓. First to 7 wins.'],breakout:['Brick Breaker','Move with ←/→ or A/D. Clear every brick.'],dodge:['Star Dodge','Move with arrow keys or WASD. Avoid the red meteors.'],memory:['Memory Match','Flip two cards and find all matching pairs.'],tictactoe:['Tic-Tac-Toe','Get three in a row against the computer.'],reaction:['Quick Draw','Wait for green, then click as fast as you can.'],math:['Math Sprint','Solve as many quick problems as you can in 30 seconds.']};
document.querySelector('#title').textContent=info[type][0];document.title=info[type][0]+' — Pixel Party';document.querySelector('#help').textContent=info[type][1];document.querySelector('#overlay-copy').textContent=info[type][1];
function ui(){scoreEl.textContent=String(score).padStart(3,'0');bestEl.textContent=String(PixelParty.profile().scores?.[type]||0).padStart(3,'0')}ui();
function begin(){cancelAnimationFrame(raf);clearInterval(timer);clearTimeout(timer);clean();clean=()=>{};score=0;active=true;overlay.classList.add('hidden');dom.innerHTML='';dom.style.display='none';canvas.style.display='block';({pong,breakout,dodge,memory,tictactoe,reaction,math}[type]||pong)();ui()}
function finish(message,points=score){if(!active)return;active=false;cancelAnimationFrame(raf);clearInterval(timer);PixelParty.award(type,Math.max(5,points),score);ui();overlay.querySelector('h2').textContent=message;overlay.querySelector('p').textContent=`Score: ${score} · +${Math.max(5,Math.floor(points))} points`;document.querySelector('#mini-start').textContent='PLAY AGAIN';overlay.classList.remove('hidden')}
document.querySelector('#mini-start').onclick=begin;
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.startsWith('Arrow'))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function base(){ctx.fillStyle='#090b11';ctx.fillRect(0,0,760,520);ctx.strokeStyle='#ffffff15';ctx.setLineDash([10,12]);ctx.beginPath();ctx.moveTo(380,0);ctx.lineTo(380,520);ctx.stroke();ctx.setLineDash([])}
function pong(){let py=210,ey=210,bx=380,by=260,vx=5,vy=3.5,you=0,cpu=0;function loop(){if(!active)return;if(keys.w||keys.arrowup)py-=7;if(keys.s||keys.arrowdown)py+=7;py=Math.max(0,Math.min(420,py));ey+=Math.sign(by-(ey+50))*3.5;bx+=vx;by+=vy;if(by<8||by>512)vy*=-1;if((bx<45&&by>py&&by<py+100)||(bx>715&&by>ey&&by<ey+100))vx*=-1.06;if(bx<0||bx>760){if(bx<0)cpu++;else you++;score=you;ui();if(you===7||cpu===7)return finish(you===7?'YOU WIN!':'CPU WINS',you*18);bx=380;by=260;vx=(bx<0?1:-1)*5}base();ctx.fillStyle='#b6f21f';ctx.fillRect(25,py,18,100);ctx.fillStyle='#55d6e8';ctx.fillRect(717,ey,18,100);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(bx,by,9,0,7);ctx.fill();ctx.font='700 44px Outfit';ctx.fillText(you,315,60);ctx.fillText(cpu,420,60);raf=requestAnimationFrame(loop)}loop()}
function breakout(){let px=320,bx=380,by=430,vx=4,vy=-5,bricks=Array.from({length:40},(_,i)=>({x:46+(i%8)*85,y:50+Math.floor(i/8)*38,on:true}));function loop(){if(!active)return;if(keys.a||keys.arrowleft)px-=8;if(keys.d||keys.arrowright)px+=8;px=Math.max(0,Math.min(640,px));bx+=vx;by+=vy;if(bx<8||bx>752)vx*=-1;if(by<8)vy*=-1;if(by>480&&by<505&&bx>px&&bx<px+120)vy=-Math.abs(vy);for(const b of bricks)if(b.on&&bx>b.x&&bx<b.x+72&&by>b.y&&by<b.y+25){b.on=false;vy*=-1;score+=10;ui();break}if(!bricks.some(b=>b.on))return finish('BOARD CLEARED!',score/2);if(by>530)return finish('BALL LOST',score/3);ctx.fillStyle='#0a0d15';ctx.fillRect(0,0,760,520);bricks.forEach((b,i)=>{if(b.on){ctx.fillStyle=['#b6f21f','#55d6e8','#ff7b45','#d878ff'][i%4];ctx.fillRect(b.x,b.y,72,25)}});ctx.fillStyle='#fff';ctx.fillRect(px,490,120,15);ctx.beginPath();ctx.arc(bx,by,8,0,7);ctx.fill();raf=requestAnimationFrame(loop)}loop()}
function dodge(){let p={x:365,y:440},rocks=[],frames=0;function loop(){if(!active)return;frames++;if(keys.a||keys.arrowleft)p.x-=7;if(keys.d||keys.arrowright)p.x+=7;if(keys.w||keys.arrowup)p.y-=7;if(keys.s||keys.arrowdown)p.y+=7;p.x=Math.max(10,Math.min(720,p.x));p.y=Math.max(10,Math.min(480,p.y));if(frames%30===0)rocks.push({x:Math.random()*730,y:-30,r:12+Math.random()*18,v:3+score/250});rocks.forEach(r=>r.y+=r.v);rocks=rocks.filter(r=>r.y<550);if(rocks.some(r=>Math.hypot(r.x-p.x,r.y-p.y)<r.r+18))return finish('METEOR HIT!',score/4);if(frames%6===0){score++;ui()}ctx.fillStyle='#080b1a';ctx.fillRect(0,0,760,520);for(let i=0;i<50;i++){ctx.fillStyle='#ffffff55';ctx.fillRect((i*97)%760,(i*53+frames)%520,2,2)}rocks.forEach(r=>{ctx.fillStyle='#ff4e5f';ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,7);ctx.fill()});ctx.fillStyle='#b6f21f';ctx.beginPath();ctx.moveTo(p.x,p.y-24);ctx.lineTo(p.x-20,p.y+20);ctx.lineTo(p.x+20,p.y+20);ctx.fill();raf=requestAnimationFrame(loop)}loop()}
function domMode(cls){canvas.style.display='none';dom.style.display='grid';dom.className=cls}
function memory(){domMode('memory-grid');const icons=['🍕','🚀','🎮','🐸','⭐','🍉','🦊','⚡'],deck=[...icons,...icons].sort(()=>Math.random()-.5);let open=[],matched=0,moves=0;dom.innerHTML=deck.map((v,i)=>`<button data-i="${i}">?</button>`).join('');dom.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(!active||open.length===2||b.classList.contains('done'))return;const i=+b.dataset.i;b.textContent=deck[i];b.classList.add('open');open.push(b);if(open.length===2){moves++;const[a,z]=open;if(deck[a.dataset.i]===deck[z.dataset.i]){a.classList.add('done');z.classList.add('done');open=[];matched+=2;score=Math.max(10,160-moves*5);ui();if(matched===16)finish('ALL MATCHED!',score)}else setTimeout(()=>{a.textContent=z.textContent='?';a.classList.remove('open');z.classList.remove('open');open=[]},650)}})}
function tictactoe(){domMode('ttt-grid');let cells=Array(9).fill('');dom.innerHTML=cells.map((_,i)=>`<button data-i="${i}"></button>`).join('');const win=a=>[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(q=>q.every(i=>a[i]===a[q[0]]&&a[i]));function paint(){dom.querySelectorAll('button').forEach((b,i)=>b.textContent=cells[i])}dom.querySelectorAll('button').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;if(!active||cells[i])return;cells[i]='X';paint();if(win(cells))return finish('YOU WIN!',100);if(cells.every(Boolean))return finish('DRAW!',25);const free=cells.map((v,i)=>v?null:i).filter(v=>v!==null);cells[free[Math.floor(Math.random()*free.length)]]='O';paint();if(win(cells))finish('CPU WINS',10)})}
function reaction(){domMode('reaction-box');dom.innerHTML='<button id="react">WAIT FOR GREEN…</button>';const b=dom.firstChild;let ready=false,start;b.onclick=()=>{if(!active)return;if(!ready)return finish('TOO SOON!',5);const ms=Math.round(performance.now()-start);score=Math.max(1,1000-ms);ui();finish(ms+' ms!',Math.max(10,Math.round(score/5)))};timer=setTimeout(()=>{ready=true;start=performance.now();b.textContent='CLICK!';b.classList.add('go')},1200+Math.random()*2800)}
function math(){domMode('math-box');let left=30,answer;dom.innerHTML='<div><b id="math-time">30s</b><h2 id="question"></h2><input id="answer" inputmode="numeric" autofocus><p>Type the answer and press Enter</p></div>';const q=()=>{const a=2+Math.floor(Math.random()*18),b=2+Math.floor(Math.random()*18),mult=Math.random()>.7;answer=mult?a*b:a+b;dom.querySelector('#question').textContent=`${a} ${mult?'×':'+'} ${b} = ?`;dom.querySelector('input').value='';dom.querySelector('input').focus()};dom.querySelector('input').onkeydown=e=>{if(e.key==='Enter'&&+e.target.value===answer){score+=10;ui();q()}};q();timer=setInterval(()=>{left--;dom.querySelector('#math-time').textContent=left+'s';if(!left)finish('TIME!',score)},1000)}
