const c=document.querySelector('#game'),ctx=c.getContext('2d'),COLS=12,ROWS=20,S=30,colors=['','#41d9ff','#ffd43b','#a97cff','#54e080','#ff5656','#ff9838','#5276ff'];
function awardTetris(){let p;try{p=JSON.parse(localStorage.getItem('pixel-party-profile')||'{}')}catch{p={}}const pts=Math.max(5,Math.floor(score/20));p.points=(p.points||0)+pts;p.scores={...(p.scores||{}),tetris:Math.max(p.scores?.tetris||0,score)};localStorage.setItem('pixel-party-profile',JSON.stringify(p));return pts}
const shapes=[[],[[1,1,1,1]],[[2,2],[2,2]],[[0,3,0],[3,3,3]],[[0,4,4],[4,4,0]],[[5,5,0],[0,5,5]],[[6,0,0],[6,6,6]],[[0,0,7],[7,7,7]]];
let board,piece,last=0,drop=700,running=false,score=0,lines=0,raf;
const overlay=document.querySelector('#overlay');
function reset(){board=Array.from({length:ROWS},()=>Array(COLS).fill(0));
score=lines=0;
drop=700;
update();
spawn();
running=true;
overlay.classList.add('hidden');
last=performance.now();
cancelAnimationFrame(raf);
raf=requestAnimationFrame(loop)}function spawn(){const id=1+Math.floor(Math.random()*7);
piece={m:shapes[id].map(r=>r.map(v=>v?id:0)),x:Math.floor(COLS/2)-Math.ceil(shapes[id][0].length/2),y:0};
if(hit(piece.x,piece.y,piece.m))over()}function hit(px,py,m){return m.some((r,y)=>r.some((v,x)=>v&&(px+x<0||px+x>=COLS||py+y>=ROWS||(py+y>=0&&board[py+y][px+x]))))}function merge(){piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v)board[piece.y+y][piece.x+x]=v}));
let n=0;
for(let y=ROWS-1;
y>=0;
y--)if(board[y].every(Boolean)){board.splice(y,1);
board.unshift(Array(COLS).fill(0));
n++;
y++}if(n){lines+=n;
score+=[0,100,300,500,800][n];
drop=Math.max(160,700-lines*14);
update()}spawn()}function move(dx,dy){if(!running)return;
if(!hit(piece.x+dx,piece.y+dy,piece.m)){piece.x+=dx;
piece.y+=dy;
return true}if(dy){merge();
return false}}function rotate(){if(!running)return;
const m=piece.m[0].map((_,i)=>piece.m.map(r=>r[i]).reverse());
for(const n of [0,-1,1,-2,2])if(!hit(piece.x+n,piece.y,m)){piece.x+=n;
piece.m=m;
break}}function hard(){if(!running)return;
let d=0;
while(move(0,1))d++;
score+=d*2;
update()}function loop(t){if(!running)return;
if(t-last>drop){move(0,1);
last=t}draw();
raf=requestAnimationFrame(loop)}function cell(v,x,y){ctx.fillStyle=colors[v];
ctx.fillRect(x*S+1,y*S+1,S-2,S-2);
ctx.fillStyle='#ffffff35';
ctx.fillRect(x*S+4,y*S+4,S-8,4);
ctx.strokeStyle='#00000035';
ctx.strokeRect(x*S+1.5,y*S+1.5,S-3,S-3)}function draw(){ctx.fillStyle='#090b0e';
ctx.fillRect(0,0,c.width,c.height);
ctx.strokeStyle='#ffffff0b';
for(let y=0;
y<ROWS;
y++)for(let x=0;
x<COLS;
x++){ctx.strokeRect(x*S,y*S,S,S);
if(board[y][x])cell(board[y][x],x,y)}if(piece)piece.m.forEach((r,y)=>r.forEach((v,x)=>v&&cell(v,piece.x+x,piece.y+y)))}function update(){document.querySelector('#score').textContent=String(score).padStart(4,'0');
document.querySelector('#lines').textContent=String(lines).padStart(2,'0')}function over(){running=false;
cancelAnimationFrame(raf);
const earned=awardTetris();
overlay.innerHTML=`<h2>STACKED OUT</h2><p>${lines} lines cleared · ${score} score · +${earned} points</p><button class="game-btn" id="again">PLAY AGAIN</button>`;
overlay.classList.remove('hidden');
document.querySelector('#again').onclick=reset}document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1,0);
if(e.key==='ArrowRight')move(1,0);
if(e.key==='ArrowDown'){move(0,1);
score++;
update()}if(e.key==='ArrowUp')rotate();
if(e.code==='Space')hard();
if(e.key.startsWith('Arrow')||e.code==='Space')e.preventDefault()});
const acts={left:()=>move(-1,0),right:()=>move(1,0),down:()=>move(0,1),rotate};
document.querySelectorAll('[data-act]').forEach(b=>b.onclick=acts[b.dataset.act]);
document.querySelector('#start').onclick=reset;
document.querySelector('#restart').onclick=reset;
board=Array.from({length:ROWS},()=>Array(COLS).fill(0));
draw();
